image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.0.0

stages:
  - build

build:
  stage: build
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -H 10.0.3.120 >> ~/.ssh/known_hosts

    - apt-get update
    - apt-get install -y libboost-filesystem-dev openssl libssl-dev 

    - cd /builds/kitsudaiki/NanamiSecret
    - ./build.sh

    - mkdir upload
    - cp ../result/NanamiSecret upload/

  artifacts:
    paths:
      - upload
    expire_in: 1 week
  tags:
    - docker

